/**
 * Builds the Windows desktop app.
 *
 *   bun run scripts/build-desktop.ts     ->  dist/desktop/
 *
 * What comes out is a single executable that is the whole application: the
 * server, the Bun runtime, and every file the frontend needs, with the hearth
 * baked in as its icon. One file to hand somebody, and what
 * scripts/build-installer.ts wraps into HearthSetup.exe.
 */
import { mkdir, rm, stat } from "node:fs/promises";
import { join } from "node:path";

const OUT = "dist/desktop";

/*
 * One place the version is written down: package.json.
 *
 * It used to be spelled out here, in package.json, and in the installer script
 * as well — three copies of a number that has to agree, which is two more than
 * can be kept honest by hand. An updater comparing what is installed against
 * what has been released cannot afford any of them to drift.
 */
const VERSION: string = JSON.parse(await Bun.file("package.json").text()).version;
const NL = String.fromCharCode(10);

await rm(OUT, { recursive: true, force: true });
await mkdir(OUT, { recursive: true });

/*
 * The frontend, written out as a module of `with { type: "file" }` imports.
 *
 * That is how Bun carries a file into a compiled binary: the import resolves
 * to a path on disk in a checkout and to a path inside the executable once
 * compiled, so the same Bun.file() call works in both. Generated rather than
 * written by hand because it has to name every asset, and one missing from the
 * list is a font or a stylesheet that 404s only in the built app — which is
 * the worst place to find out.
 */
console.log("  Listing the frontend ...");
const assets = [...new Bun.Glob("**/*").scanSync("public")]
  .map((f) => f.split("\\").join("/"))
  .sort();

const header = [
  "/**",
  " * Generated by scripts/build-desktop.ts - do not edit.",
  " *",
  " * Every file under public/, imported so that `bun build --compile` carries",
  " * it inside the executable. Maps a request path to something Bun.file() can",
  " * read: a path on disk in a checkout, a path inside the binary once built.",
  " */",
];
const imports = assets.map((f, i) => `import f${i} from "../public/${f}" with { type: "file" };`);
const entries = assets.map((f, i) => `  "/${f}": f${i},`);

await Bun.write("src/embedded.generated.ts", [
  ...header,
  ...imports,
  "",
  "// Loosely typed on the way in: Bun types an .html import as an HTMLBundle",
  "// rather than a string, and every value here is only ever a path.",
  "const files: Record<string, unknown> = {",
  ...entries,
  "};",
  "",
  "export const FILES = files as Record<string, string>;",
  "",
].join(NL));
console.log(`  ${assets.length} files carried inside the binary`);

await Bun.write("src/version.generated.ts", [
  "/**",
  " * Generated by scripts/build-desktop.ts - do not edit.",
  " *",
  " * What this build calls itself, taken from package.json at build time so a",
  " * running Hearth can say which one it is.",
  " */",
  `export const VERSION = ${JSON.stringify(VERSION)};`,
  "",
].join(NL));

console.log("  Compiling Hearth.exe ...");
// An argv array rather than Bun's shell: the flag list is long enough to want
// wrapping, and the shell reads a wrapped line as several commands.
const build = Bun.spawnSync(["bun", "build", "--compile", "src/desktop.ts",
  "--outfile", join(OUT, "Hearth.exe"),
  "--windows-icon", "installer/hearth.ico",
  "--windows-hide-console",
  "--windows-title", "Hearth",
  "--windows-description", "Hearth — local-first roleplay",
  "--windows-version", `${VERSION}.0`,
], { stdout: "pipe", stderr: "pipe" });

if (build.exitCode !== 0) {
  console.error(build.stderr.toString() || build.stdout.toString());
  process.exit(1);
}

const size = (await stat(join(OUT, "Hearth.exe"))).size;
console.log(`${NL}  dist/desktop  —  Hearth.exe is ${(size / 1024 / 1024).toFixed(1)} MB`);
console.log("  That one file is the whole app: no folder, nothing beside it.");
console.log(`  scripts/build-installer.ts wraps it into a setup wizard.${NL}`);
