/**
 * Generated by scripts/build-desktop.ts - do not edit.
 *
 * What this build calls itself, taken from package.json at build time so a
 * running Hearth can say which one it is.
 */
export const VERSION = "0.2.1";
